# First-draft diagnostic instrument database for QAS_Mv3
#
# Automatically created from:
# - QAS_Mv3_hour.csv
#
# First CSV timestamp:
# 2023-08-31 20:00:00
#
# Reviewed boundaries:
# - 2024-09-01
# - 2025-09-01

[[sensor]]
name = "instrument_1"

#  - CSV data-start boundary only.
installation_date = "2023-08-31"

decommission_date = "2024-09-01"

instrument_type = "NA"
serial_number = "NA"
source_file = "QAS_Mv3_hour.csv"
parsing_confidence = "csv_data_start_only_review_required"


[[sensor]]
name = "instrument_2"

installation_date = "2024-09-01"
decommission_date = "2025-09-01"

instrument_type = "NA"
serial_number = "NA"
source_file = "maintenance sheets/QAS_Mv3_2024.pdf"
parsing_confidence = "reviewed_date"


[[sensor]]
name = "instrument_3"

installation_date = "2025-09-01"
decommission_date = "NA"

instrument_type = "NA"
serial_number = "NA"
source_file = "maintenance sheets/QAS_M_2025.pdf"
parsing_confidence = "reviewed_date"